In [50]:
import pandas as pd

df = pd.read_csv('tagalogdefinitionpure.csv')
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

df.head

Rows: 45831, Columns: 2

<bound method NDFrame.head of              word                                         definition
0      aalug-alog                     aalug-alog adj. shaky; rickety
1             aam                 aam n. broth made from boiled rice
2      aanga-anga      aanga-anga adj. remaining agape for some time
3        aapa-apa                       aapa-apa adj. groping around
4             aba                 aba adj. poor; humble; subservient
...           ...                                                ...
45826    Yuropyum                       n. Europium (Eu) (chemistry)
45827        yuta                     yuta n., adj. hundred thousand
45828      yutyot  yutyot n. intermittent shaking (like a house w...
45829        zink                               n. zinc (Zn) (metal)
45830         zoo                                             n. zoo

[45831 rows x 2 columns]>

In [51]:
df_filtered = df[df['word'].notna()]
df_filtered

df_filtered.head

<bound method NDFrame.head of              word                                         definition
0      aalug-alog                     aalug-alog adj. shaky; rickety
1             aam                 aam n. broth made from boiled rice
2      aanga-anga      aanga-anga adj. remaining agape for some time
3        aapa-apa                       aapa-apa adj. groping around
4             aba                 aba adj. poor; humble; subservient
...           ...                                                ...
45826    Yuropyum                       n. Europium (Eu) (chemistry)
45827        yuta                     yuta n., adj. hundred thousand
45828      yutyot  yutyot n. intermittent shaking (like a house w...
45829        zink                               n. zinc (Zn) (metal)
45830         zoo                                             n. zoo

[45831 rows x 2 columns]>

In [52]:
df['word'] = df['word'].str.upper()
df.head()

         word                                     definition
0  AALUG-ALOG                 aalug-alog adj. shaky; rickety
1         AAM             aam n. broth made from boiled rice
2  AANGA-ANGA  aanga-anga adj. remaining agape for some time
3    AAPA-APA                   aapa-apa adj. groping around
4         ABA             aba adj. poor; humble; subservient

In [53]:
# remove (...) and [...]
df["definition"] = (
    df["definition"]
      .str.replace(r"\s*\([^)]*\)", "", regex=True)   # remove ( ... )
      .str.replace(r"\s*\[[^\]]*\]", "", regex=True)  # remove [ ... ]
      .str.replace(r"\s{2,}", " ", regex=True)        # collapse multiple spaces
      .str.strip()
)
df.head

<bound method NDFrame.head of              word                                     definition
0      AALUG-ALOG                 aalug-alog adj. shaky; rickety
1             AAM             aam n. broth made from boiled rice
2      AANGA-ANGA  aanga-anga adj. remaining agape for some time
3        AAPA-APA                   aapa-apa adj. groping around
4             ABA             aba adj. poor; humble; subservient
...           ...                                            ...
45826    YUROPYUM                                    n. Europium
45827        YUTA                 yuta n., adj. hundred thousand
45828      YUTYOT                 yutyot n. intermittent shaking
45829        ZINK                                        n. zinc
45830         ZOO                                         n. zoo

[45831 rows x 2 columns]>

In [54]:
pos = ["n", "adj", "v", "comp", "inf", "conj", "prep", "pron", "lit", "fig", "pl", "adv", "intrj", "bot", "ref", "med", "mat" , "zoo", "gram", "pref", "Interrog.", " Expr."]

pos_pat = r"(?i)\b(?:%s)\.(?=\s|$|[,\;\:\)\]])" % "|".join(pos)

df["definition"] = (
    df["definition"]
      .str.replace(pos_pat, "", regex=True)          # drop POS tags
      .str.replace(r"\s{2,}", " ", regex=True)       # collapse spaces
      .str.replace(r"\s+([,;:])", r"\1", regex=True) # remove space before punctuation
      .str.strip()
)

df.head

<bound method NDFrame.head of              word                                definition
0      AALUG-ALOG                 aalug-alog shaky; rickety
1             AAM           aam broth made from boiled rice
2      AANGA-ANGA  aanga-anga remaining agape for some time
3        AAPA-APA                   aapa-apa groping around
4             ABA             aba poor; humble; subservient
...           ...                                       ...
45826    YUROPYUM                                  Europium
45827        YUTA                    yuta, hundred thousand
45828      YUTYOT               yutyot intermittent shaking
45829        ZINK                                      zinc
45830         ZOO                                       zoo

[45831 rows x 2 columns]>

In [55]:
df[df["word"].str.upper().str.contains(r"\bABAY\b", na=False)]

                    word                                         definition
36                  ABAY          abay lying or sitting close to each other
37                  ABAY  1. best man at a wedding; maid of honour; 2. e...
38          ABAY (MGA -)                     , retinue; group of attendants
39         ABAY NA BABAE                                         bridesmaid
40        ABAY NA LALAKI                                           best man
41     ABAY NA PANDANGAL                           pandangal maid of honour
19128           MAG-ABAY           mag-abay, lie or sit close to each other
34447          PANG-ABAY                                             adverb

In [56]:
df["definition"] = df["definition"].str.replace(r"^\s*,\s*|,\s*$", "", regex=True).str.strip()

In [57]:
df

             word                                definition
0      AALUG-ALOG                 aalug-alog shaky; rickety
1             AAM           aam broth made from boiled rice
2      AANGA-ANGA  aanga-anga remaining agape for some time
3        AAPA-APA                   aapa-apa groping around
4             ABA             aba poor; humble; subservient
...           ...                                       ...
45826    YUROPYUM                                  Europium
45827        YUTA                    yuta, hundred thousand
45828      YUTYOT               yutyot intermittent shaking
45829        ZINK                                      zinc
45830         ZOO                                       zoo

[45831 rows x 2 columns]

In [58]:
df[df["word"].str.upper().str.contains(r"\bABAY\b", na=False)]

                    word                                         definition
36                  ABAY          abay lying or sitting close to each other
37                  ABAY  1. best man at a wedding; maid of honour; 2. e...
38          ABAY (MGA -)                       retinue; group of attendants
39         ABAY NA BABAE                                         bridesmaid
40        ABAY NA LALAKI                                           best man
41     ABAY NA PANDANGAL                           pandangal maid of honour
19128           MAG-ABAY           mag-abay, lie or sit close to each other
34447          PANG-ABAY                                             adverb

In [59]:
df[df["word"].str.upper().str.contains(r"\bBAHAGI\b", na=False)]

,word,definition
1905,BAHAGI,partial; part
1906,BAHAGI,1. part; 2. portion; 3. element; 4. angle; 5. ...
1907,BAHAGI NG PANANALITA,"bahagi ng pananalita, part of speach"
10188,IKAAPAT NA BAHAGI,a quarter; one fourth
10284,IKASAMPUNG BAHAGI,"ikasampung bahagi, tithe; one tenth"
10305,IKATLONG BAHAGI,"ikatlong, one third"
19570,MAGBAHA-BAHAGI,"magbaha-bahagi, apportion; divide and give out..."
26782,MAY TATLONG BAHAGI,may tatlong bahagi tripartite; threefold
29604,PAGBABAHA-BAHAGI,pagbabaha-bahagi 1. partition; 2. division of ...
30653,PAGKAKABAHA-BAHAGI,pagkakabaha-bahagi 1. division; 2. split
36843,"PINAKAMAHALAGANG BAHAGI, ANG -",pinakamahalagang body; the main part

In [60]:
df["definition"] = (
    df["definition"]
      .str.replace(r"(?<!\d)\b\d{1,2}\s*\.\s*", "", regex=True)
      .str.replace(r"\s{2,}", " ", regex=True)
      .str.strip()
)

In [61]:
df[df["word"].str.upper().str.contains(r"\bBAHAGI\b", na=False)]

,word,definition
1905,BAHAGI,partial; part
1906,BAHAGI,part; portion; element; angle; organ; share; d...
1907,BAHAGI NG PANANALITA,"bahagi ng pananalita, part of speach"
10188,IKAAPAT NA BAHAGI,a quarter; one fourth
10284,IKASAMPUNG BAHAGI,"ikasampung bahagi, tithe; one tenth"
10305,IKATLONG BAHAGI,"ikatlong, one third"
19570,MAGBAHA-BAHAGI,"magbaha-bahagi, apportion; divide and give out..."
26782,MAY TATLONG BAHAGI,may tatlong bahagi tripartite; threefold
29604,PAGBABAHA-BAHAGI,pagbabaha-bahagi partition; division of numbers
30653,PAGKAKABAHA-BAHAGI,pagkakabaha-bahagi division; split
36843,"PINAKAMAHALAGANG BAHAGI, ANG -",pinakamahalagang body; the main part

In [62]:
import re
import pandas as pd

def remove_exact_word_from_clue(row):
    w = str(row["word"]).strip()
    c = str(row["definition"])

    if not w or pd.isna(row["definition"]):
        return row["definition"]

    # match Word as a whole token (not inside other words), case-insensitive
    pat = re.compile(rf"(?i)(?<![A-Za-z0-9]){re.escape(w)}(?![A-Za-z0-9])")

    # remove (optionally remove only the first occurrence: count=1)
    c = pat.sub("", c, count=1)

    # cleanup: extra spaces + leading punctuation left behind
    c = re.sub(r"\s{2,}", " ", c).strip()
    c = re.sub(r"^[\s,;:\-–—]+", "", c).strip()

    return c

df["definition"] = df.apply(remove_exact_word_from_clue, axis=1)

In [63]:
df

             word                     definition
0      AALUG-ALOG                 shaky; rickety
1             AAM    broth made from boiled rice
2      AANGA-ANGA  remaining agape for some time
3        AAPA-APA                 groping around
4             ABA      poor; humble; subservient
...           ...                            ...
45826    YUROPYUM                       Europium
45827        YUTA               hundred thousand
45828      YUTYOT           intermittent shaking
45829        ZINK                           zinc
45830         ZOO

[45831 rows x 2 columns]

In [64]:
df[df["definition"].astype(str).str.strip().eq("")]

            word definition
181        ADULT
513        ALBUM
911      ANDANTE
1132   APARTMENT
1282       ARGON
...          ...        ...
45628       WATT
45632        WAX
45722       YARD
45774       YOGA
45830        ZOO

[226 rows x 2 columns]

In [65]:
df = df[~(df["definition"].isna() | df["definition"].astype(str).str.strip().eq(""))].reset_index(drop=True)

In [66]:
df

             word                     definition
0      AALUG-ALOG                 shaky; rickety
1             AAM    broth made from boiled rice
2      AANGA-ANGA  remaining agape for some time
3        AAPA-APA                 groping around
4             ABA      poor; humble; subservient
...           ...                            ...
45600     YURAKAN           tread on; trample on
45601    YUROPYUM                       Europium
45602        YUTA               hundred thousand
45603      YUTYOT           intermittent shaking
45604        ZINK                           zinc

[45605 rows x 2 columns]

In [67]:
# split on semicolons and explode into new rows
out = (
    df.assign(definition=df["definition"].str.split(r"\s*;\s*"))
      .explode("definition", ignore_index=True)
)

# clean up (drop empties, trim)
out["definition"] = out["definition"].str.strip()
out = out[out["definition"].ne("")].reset_index(drop=True)

out

             word                     definition
0      AALUG-ALOG                          shaky
1      AALUG-ALOG                        rickety
2             AAM    broth made from boiled rice
3      AANGA-ANGA  remaining agape for some time
4        AAPA-APA                 groping around
...           ...                            ...
83297     YURAKAN                     trample on
83298    YUROPYUM                       Europium
83299        YUTA               hundred thousand
83300      YUTYOT           intermittent shaking
83301        ZINK                           zinc

[83302 rows x 2 columns]

In [68]:
out[out["word"].str.upper().str.contains(r"\bBAHAGI\b", na=False)]

                                 word                          definition
3056                           BAHAGI                             partial
3057                           BAHAGI                                part
3058                           BAHAGI                                part
3059                           BAHAGI                             portion
3060                           BAHAGI                             element
3061                           BAHAGI                               angle
3062                           BAHAGI                               organ
3063                           BAHAGI                               share
3064                           BAHAGI                                deal
3065                           BAHAGI                          proportion
3066                           BAHAGI                             segment
3067                           BAHAGI                           component
3068             BAHAGI NG PANANALITA                      part of speach
17647               IKAAPAT NA BAHAGI                           a quarter
17648               IKAAPAT NA BAHAGI                          one fourth
17784               IKASAMPUNG BAHAGI                               tithe
17785               IKASAMPUNG BAHAGI                           one tenth
17812                 IKATLONG BAHAGI                 ikatlong, one third
34811                  MAGBAHA-BAHAGI                           apportion
34812                  MAGBAHA-BAHAGI  divide and give out in fair shares
48250              MAY TATLONG BAHAGI                          tripartite
48251              MAY TATLONG BAHAGI                           threefold
53347                PAGBABAHA-BAHAGI                           partition
53348                PAGBABAHA-BAHAGI                 division of numbers
55328              PAGKAKABAHA-BAHAGI                            division
55329              PAGKAKABAHA-BAHAGI                               split
66907  PINAKAMAHALAGANG BAHAGI, ANG -               pinakamahalagang body
66908  PINAKAMAHALAGANG BAHAGI, ANG -                       the main part

In [69]:
mask = out["word"].str.contains(r"[^\w\s]", na=False)
out.loc[mask, ["word", "definition"]]
out

             word                     definition
0      AALUG-ALOG                          shaky
1      AALUG-ALOG                        rickety
2             AAM    broth made from boiled rice
3      AANGA-ANGA  remaining agape for some time
4        AAPA-APA                 groping around
...           ...                            ...
83297     YURAKAN                     trample on
83298    YUROPYUM                       Europium
83299        YUTA               hundred thousand
83300      YUTYOT           intermittent shaking
83301        ZINK                           zinc

[83302 rows x 2 columns]

In [70]:
out[out["word"].str.upper().str.contains(r"\bBAHAGI\b", na=False)]

                                 word                          definition
3056                           BAHAGI                             partial
3057                           BAHAGI                                part
3058                           BAHAGI                                part
3059                           BAHAGI                             portion
3060                           BAHAGI                             element
3061                           BAHAGI                               angle
3062                           BAHAGI                               organ
3063                           BAHAGI                               share
3064                           BAHAGI                                deal
3065                           BAHAGI                          proportion
3066                           BAHAGI                             segment
3067                           BAHAGI                           component
3068             BAHAGI NG PANANALITA                      part of speach
17647               IKAAPAT NA BAHAGI                           a quarter
17648               IKAAPAT NA BAHAGI                          one fourth
17784               IKASAMPUNG BAHAGI                               tithe
17785               IKASAMPUNG BAHAGI                           one tenth
17812                 IKATLONG BAHAGI                 ikatlong, one third
34811                  MAGBAHA-BAHAGI                           apportion
34812                  MAGBAHA-BAHAGI  divide and give out in fair shares
48250              MAY TATLONG BAHAGI                          tripartite
48251              MAY TATLONG BAHAGI                           threefold
53347                PAGBABAHA-BAHAGI                           partition
53348                PAGBABAHA-BAHAGI                 division of numbers
55328              PAGKAKABAHA-BAHAGI                            division
55329              PAGKAKABAHA-BAHAGI                               split
66907  PINAKAMAHALAGANG BAHAGI, ANG -               pinakamahalagang body
66908  PINAKAMAHALAGANG BAHAGI, ANG -                       the main part

In [71]:
out[out["word"].str.upper().str.contains(r"\bABAY\b", na=False)]

                    word                            definition
63                  ABAY  lying or sitting close to each other
64                  ABAY                 best man at a wedding
65                  ABAY                        maid of honour
66                  ABAY                                escort
67                  ABAY                             attendant
68          ABAY (MGA -)                               retinue
69          ABAY (MGA -)                   group of attendants
70         ABAY NA BABAE                            bridesmaid
71        ABAY NA LALAKI                              best man
72     ABAY NA PANDANGAL              pandangal maid of honour
34006           MAG-ABAY        lie or sit close to each other
62586          PANG-ABAY                                adverb

In [72]:
out = (
    out.assign(
        _w=out["word"].str.casefold().str.strip(),
        _d=out["definition"].str.casefold().str.strip(),
    )
    .drop_duplicates(subset=["_w", "_d"])
    .drop(columns=["_w", "_d"])
    .reset_index(drop=True)
)

In [73]:
out

             word                     definition
0      AALUG-ALOG                          shaky
1      AALUG-ALOG                        rickety
2             AAM    broth made from boiled rice
3      AANGA-ANGA  remaining agape for some time
4        AAPA-APA                 groping around
...           ...                            ...
82925     YURAKAN                     trample on
82926    YUROPYUM                       Europium
82927        YUTA               hundred thousand
82928      YUTYOT           intermittent shaking
82929        ZINK                           zinc

[82930 rows x 2 columns]

In [74]:
df = out

In [75]:
import pandas as pd

df.insert(0, "Date", pd.Timestamp.today().normalize().date())
df

             Date        word                     definition
0      2025-12-14  AALUG-ALOG                          shaky
1      2025-12-14  AALUG-ALOG                        rickety
2      2025-12-14         AAM    broth made from boiled rice
3      2025-12-14  AANGA-ANGA  remaining agape for some time
4      2025-12-14    AAPA-APA                 groping around
...           ...         ...                            ...
82925  2025-12-14     YURAKAN                     trample on
82926  2025-12-14    YUROPYUM                       Europium
82927  2025-12-14        YUTA               hundred thousand
82928  2025-12-14      YUTYOT           intermittent shaking
82929  2025-12-14        ZINK                           zinc

[82930 rows x 3 columns]

In [76]:
df = df.rename(columns={"Date": "Date", "word": "Word", "definition": "Clue"})
# or if you just want to force the exact 3 headers by position:
# df.columns = ["Date", "Word", "Clue"]
df

             Date        Word                           Clue
0      2025-12-14  AALUG-ALOG                          shaky
1      2025-12-14  AALUG-ALOG                        rickety
2      2025-12-14         AAM    broth made from boiled rice
3      2025-12-14  AANGA-ANGA  remaining agape for some time
4      2025-12-14    AAPA-APA                 groping around
...           ...         ...                            ...
82925  2025-12-14     YURAKAN                     trample on
82926  2025-12-14    YUROPYUM                       Europium
82927  2025-12-14        YUTA               hundred thousand
82928  2025-12-14      YUTYOT           intermittent shaking
82929  2025-12-14        ZINK                           zinc

[82930 rows x 3 columns]

In [77]:
df = df[df["Word"].str.casefold().ne(df["Clue"].str.casefold())].reset_index(drop=True)
df

             Date        Word                           Clue
0      2025-12-14  AALUG-ALOG                          shaky
1      2025-12-14  AALUG-ALOG                        rickety
2      2025-12-14         AAM    broth made from boiled rice
3      2025-12-14  AANGA-ANGA  remaining agape for some time
4      2025-12-14    AAPA-APA                 groping around
...           ...         ...                            ...
82769  2025-12-14     YURAKAN                     trample on
82770  2025-12-14    YUROPYUM                       Europium
82771  2025-12-14        YUTA               hundred thousand
82772  2025-12-14      YUTYOT           intermittent shaking
82773  2025-12-14        ZINK                           zinc

[82774 rows x 3 columns]

In [78]:
df[df["Word"].str.upper().str.contains(r"\bAAPA-APA\b", na=False)]

         Date      Word            Clue
4  2025-12-14  AAPA-APA  groping around

In [79]:
df[df["Clue"].eq("groping around")][["Word","Clue"]]

       Word            Clue
4  AAPA-APA  groping around

In [80]:
import pandas as pd
import re
from difflib import SequenceMatcher

df0 = df.copy()  # keep original safe

# -----------------------
# Similarity filter
# -----------------------
def _norm(s: str) -> str:
    # normalize for comparisons (remove punctuation/hyphens/spaces, lowercase)
    return re.sub(r"[^A-Za-z0-9]+", "", str(s)).casefold()

def too_similar(word: str, clue_word: str, min_root=4, ratio_thresh=0.85) -> bool:
    w, c = _norm(word), _norm(clue_word)
    if not w or not c:
        return False
    if w == c:
        return True

    # Reject prefix/containment like TALA vs TALAAN
    short = min(len(w), len(c))
    if short >= min_root and (w.startswith(c) or c.startswith(w) or w in c or c in w):
        return True

    # Reject high similarity like ITAHI vs IPAGTAHI, SOOLOHIA vs SOOLOHIYA
    if SequenceMatcher(None, w, c).ratio() >= ratio_thresh:
        return True

    return False

# -----------------------
# Base cleaned view (no deletion from df0)
# -----------------------
base = (
    df0[["Date", "Word", "Clue"]]
      .dropna(subset=["Word", "Clue"])
      .assign(
          Word=lambda x: x["Word"].astype(str).str.strip(),
          Clue=lambda x: x["Clue"].astype(str).str.strip(),
      )
)

# Find which clues are unique vs shared
clue_counts = base.groupby("Clue")["Word"].nunique()
unique_clue_values = clue_counts[clue_counts == 1].index
shared_clue_values = clue_counts[clue_counts > 1].index

# -----------------------
# uniqueclues: keep original rows with unique clue
# -----------------------
uniqueclues = base[base["Clue"].isin(unique_clue_values)].copy()

# -----------------------
# synonymclues: for shared clues, generate Word->Word clue rows
# -----------------------
shared = (
    base[base["Clue"].isin(shared_clue_values)]
      .drop_duplicates(subset=["Clue", "Word"])  # avoid duplicates inside a clue-group
)

def make_synonym_rows(g: pd.DataFrame) -> pd.DataFrame:
    words = g["Word"].unique().tolist()
    date_by_word = g.drop_duplicates("Word").set_index("Word")["Date"]

    rows = []
    for w1 in words:
        for w2 in words:
            if w1 == w2:
                continue
            if too_similar(w1, w2):
                continue
            rows.append({"Date": date_by_word[w1], "Word": w1, "Clue": w2})
    return pd.DataFrame(rows)

synonymclues = (
    shared.groupby("Clue", group_keys=False)
          .apply(make_synonym_rows)
          .drop_duplicates(subset=["Word", "Clue"])
          .reset_index(drop=True)
)

# -----------------------
# uniqueclues: UNIQUE WORDS (no Tagalog synonym rows created)
# -----------------------
words_with_synonyms = set(synonymclues["Word"])

uniqueclues = base[~base["Word"].isin(words_with_synonyms)].copy()
# (optional) remove duplicate original rows
uniqueclues = uniqueclues.drop_duplicates(subset=["Word", "Clue"]).reset_index(drop=True)

# -----------------------
# allclues = synonymclues + uniqueclues
# -----------------------
allclues = (
    pd.concat([synonymclues, uniqueclues], ignore_index=True)
      .drop_duplicates(subset=["Word", "Clue"])
      .reset_index(drop=True)
)

C:\Users\Gio\AppData\Local\Temp\ipykernel_16760\195590504.py:78: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(make_synonym_rows)

In [81]:
allclues

              Date        Word                                         Clue
0       2025-12-14        HALE                                         HALI
1       2025-12-14        HALI                                         HALE
2       2025-12-14      BALAGA                                       BULAGA
3       2025-12-14      BULAGA                                       BALAGA
4       2025-12-14        HALA                                        LARGA
...            ...         ...                                          ...
217042  2025-12-14  YUNGYUNGAN    extend one's power/influence over someone
217043  2025-12-14  YUNGYUNGAN  put under one's protection, or some shelter
217044  2025-12-14    YUROPYUM                                     Europium
217045  2025-12-14      YUTYOT                         intermittent shaking
217046  2025-12-14        ZINK                                         zinc

[217047 rows x 3 columns]

In [82]:
allclues[allclues["Word"].str.upper().str.contains(r"\bAAPA-APA\b", na=False)]

              Date      Word            Clue
196737  2025-12-14  AAPA-APA  groping around

In [83]:
# import itertools
# import pandas as pd

# def levenshtein(a: str, b: str) -> int:
#     # small/fast DP for short strings
#     if a == b: 
#         return 0
#     if not a:
#         return len(b)
#     if not b:
#         return len(a)
#     if len(a) > len(b):
#         a, b = b, a

#     prev = list(range(len(b) + 1))
#     for i, ca in enumerate(a, 1):
#         cur = [i]
#         for j, cb in enumerate(b, 1):
#             ins = cur[j - 1] + 1
#             dele = prev[j] + 1
#             sub = prev[j - 1] + (ca != cb)
#             cur.append(min(ins, dele, sub))
#         prev = cur
#     return prev[-1]

# # df columns assumed: Date, Word, Clue
# base = (
#     df[["Date", "Word", "Clue"]]
#       .dropna(subset=["Word", "Clue"])
#       .assign(
#           Word=lambda x: x["Word"].astype(str).str.strip(),
#           Clue=lambda x: x["Clue"].astype(str).str.strip(),
#       )
#       .drop_duplicates(subset=["Word", "Clue"])
# )

# def make_synonym_rows(g: pd.DataFrame) -> pd.DataFrame:
#     words = g["Word"].unique().tolist()
#     rows = []
#     for w1, w2 in itertools.permutations(words, 2):
#         rows.append({"Date": g["Date"].iloc[0], "Word": w1, "Clue": w2})
#     return pd.DataFrame(rows)

# synonym_clues = (
#     base.groupby("Clue", group_keys=False)
#         .apply(make_synonym_rows)
#         .drop_duplicates(subset=["Word", "Clue"])
#         .reset_index(drop=True)
# )

# df_augmented = (
#     pd.concat([base, synonym_clues], ignore_index=True)
#       .drop_duplicates(subset=["Word", "Clue"])
#       .reset_index(drop=True)
# )

In [84]:
allclues["Clue"] = (
    allclues["Clue"].astype(str).str.strip().str.lower().str.capitalize()
)

In [85]:
allclues

              Date        Word                                         Clue
0       2025-12-14        HALE                                         Hali
1       2025-12-14        HALI                                         Hale
2       2025-12-14      BALAGA                                       Bulaga
3       2025-12-14      BULAGA                                       Balaga
4       2025-12-14        HALA                                        Larga
...            ...         ...                                          ...
217042  2025-12-14  YUNGYUNGAN    Extend one's power/influence over someone
217043  2025-12-14  YUNGYUNGAN  Put under one's protection, or some shelter
217044  2025-12-14    YUROPYUM                                     Europium
217045  2025-12-14      YUTYOT                         Intermittent shaking
217046  2025-12-14        ZINK                                         Zinc

[217047 rows x 3 columns]

In [86]:
# out[out["word"].str.upper().str.contains(r"\bABAY\b", na=False)]

allclues[allclues["Word"].str.upper().str.contains(r"\bAAPA-APA\b", na=False)]

              Date      Word            Clue
196737  2025-12-14  AAPA-APA  Groping around

In [87]:
import pandas as pd

# Base original rows (word + original clue)
base = (
    df[["Date", "Word", "Clue"]]
      .dropna(subset=["Word", "Clue"])
      .assign(
          Word=lambda x: x["Word"].astype(str).str.strip(),
          Clue=lambda x: x["Clue"].astype(str).str.strip(),
      )
      .drop_duplicates(subset=["Word", "Clue"])
)

# Rows whose clue appears for only ONE word (no synonyms possible)
clue_counts = base.groupby("Clue")["Word"].nunique()
unique_clues = clue_counts[clue_counts == 1].index
unique_rows = base[base["Clue"].isin(unique_clues)]

# Only keep those words if they are NOT already present in synonym_clues
unique_rows = unique_rows[~unique_rows["Word"].isin(allclues["Word"])]

# Append + de-dupe
df_clues = (
    pd.concat([allclues, unique_rows], ignore_index=True)
      .drop_duplicates(subset=["Word", "Clue"])
      .reset_index(drop=True)
)

# Clue: capitalize first letter only
df_clues["Clue"] = (
    df_clues["Clue"].astype(str).str.strip().str.lower().str.capitalize()
)
df_clues

              Date        Word                                         Clue
0       2025-12-14        HALE                                         Hali
1       2025-12-14        HALI                                         Hale
2       2025-12-14      BALAGA                                       Bulaga
3       2025-12-14      BULAGA                                       Balaga
4       2025-12-14        HALA                                        Larga
...            ...         ...                                          ...
217042  2025-12-14  YUNGYUNGAN    Extend one's power/influence over someone
217043  2025-12-14  YUNGYUNGAN  Put under one's protection, or some shelter
217044  2025-12-14    YUROPYUM                                     Europium
217045  2025-12-14      YUTYOT                         Intermittent shaking
217046  2025-12-14        ZINK                                         Zinc

[217047 rows x 3 columns]

In [88]:
import re

def _alnum(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "", str(s)).casefold()

def word_is_in_clue(row, min_len=3):
    w = _alnum(row["Word"])
    c = _alnum(row["Clue"])
    if len(w) < min_len:
        return False
    return w in c

df_clues = df_clues[~df_clues.apply(word_is_in_clue, axis=1)].reset_index(drop=True)

In [89]:
df_clues

              Date        Word                                         Clue
0       2025-12-14        HALE                                         Hali
1       2025-12-14        HALI                                         Hale
2       2025-12-14      BALAGA                                       Bulaga
3       2025-12-14      BULAGA                                       Balaga
4       2025-12-14        HALA                                        Larga
...            ...         ...                                          ...
216877  2025-12-14  YUNGYUNGAN    Extend one's power/influence over someone
216878  2025-12-14  YUNGYUNGAN  Put under one's protection, or some shelter
216879  2025-12-14    YUROPYUM                                     Europium
216880  2025-12-14      YUTYOT                         Intermittent shaking
216881  2025-12-14        ZINK                                         Zinc

[216882 rows x 3 columns]

In [90]:
import re
from difflib import SequenceMatcher

def _norm(s: str) -> str:
    # normalize: keep letters/numbers only, lowercase
    return re.sub(r"[^A-Za-z0-9]+", "", str(s)).casefold()

def similarity(a: str, b: str) -> float:
    a, b = _norm(a), _norm(b)
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a, b).ratio()

# tune this threshold
THRESH = 0.60  # try 0.80–0.90 depending on how aggressive you want

mask_too_similar = df_clues.apply(
    lambda r: similarity(r["Word"], r["Clue"]) >= THRESH,
    axis=1
)

df_clues = df_clues[~mask_too_similar].reset_index(drop=True)
df_clues

,Date,Word,Clue
0,2025-12-14,HALA,Larga
1,2025-12-14,LARGA,Hala
2,2025-12-14,HINTO,Tahan
3,2025-12-14,TAHAN,Hinto
4,2025-12-14,MAG-UTOS NANG MAG-UTOS,Utusan nang utusan
...,...,...,...
187247,2025-12-14,YUMUNGYONG,Project over
187248,2025-12-14,YUNGIB NG ASIN,Salt dome
187249,2025-12-14,YUNGYUNGAN,Extend one's power/influence over someone
187250,2025-12-14,YUNGYUNGAN,"Put under one's protection, or some shelter"
187251,2025-12-14,YUTYOT,Intermittent shaking

In [91]:
print(similarity("IKOLA", "Magkola"))

0.6666666666666666

In [92]:
df_clues["Word"] = df_clues["Word"].astype(str).str.replace(r"\s+", "", regex=True)


df = df_clues

# (optional) normalize word column first (you already do this)
df["Word"] = df["Word"].str.upper()

df["Word"] = (
    df["Word"]
      .str.replace(r"\s*\([^)]*\)\s*", "", regex=True)  # remove (...) anywhere
      .str.strip()
)


df["Word"] = (
    df["Word"]
      .str.replace(r"[^A-Za-z\s]", "", regex=True)
      .str.replace(r"\s+", " ", regex=True)
      .str.strip()
)

mask = df["Word"].str.contains(r"[^\w\s]", na=False)
df[mask]

Empty DataFrame
Columns: [Date, Word, Clue]
Index: []

In [93]:
df

,Date,Word,Clue
0,2025-12-14,HALA,Larga
1,2025-12-14,LARGA,Hala
2,2025-12-14,HINTO,Tahan
3,2025-12-14,TAHAN,Hinto
4,2025-12-14,MAGUTOSNANGMAGUTOS,Utusan nang utusan
...,...,...,...
187247,2025-12-14,YUMUNGYONG,Project over
187248,2025-12-14,YUNGIBNGASIN,Salt dome
187249,2025-12-14,YUNGYUNGAN,Extend one's power/influence over someone
187250,2025-12-14,YUNGYUNGAN,"Put under one's protection, or some shelter"
187251,2025-12-14,YUTYOT,Intermittent shaking

In [104]:
df = df[df["Word"].astype(str).str.len().ge(3)].reset_index(drop=True)

In [105]:
df[df["Word"].astype(str).str.len() < 3]

Empty DataFrame
Columns: [Date, Word, Clue]
Index: []

In [106]:
df.to_csv("tagalogcrosswordfinal_test.csv", index=False)