In [2]:
import pandas as pd

url = "https://tl.wikipedia.org/wiki/Talaan_ng_mga_lungsod_at_bayan_sa_Pilipinas"

# This returns a list of DataFrames for ALL tables on the page
tables = pd.read_html(url)

# On this page, the big “Talaan” table is typically the largest one
df = max(tables, key=lambda t: t.shape[0])

print(df.shape)
print(df.head())

HTTPError: HTTP Error 403: Forbidden

In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

url = "https://tl.wikipedia.org/wiki/Talaan_ng_mga_lungsod_at_bayan_sa_Pilipinas"
html = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}).text
soup = BeautifulSoup(html, "html.parser")

table = soup.select_one("table.wikitable.sortable.plainrowheaders.mw-datatable")
df = pd.read_html(str(table))[0]

print(df.shape)
print(df.head())

(1635, 10)
  Lungsod o bayan Populasyon (2015)[1] Lawak/sukat (km2)[i][2][3]  \
0         Bangued                48163                     105.70
1         Boliney                 3573                     216.92
2           Bucay                17115                     107.17
3          Bucloc                 2501                      63.77
4       Daguioman                 2088                     114.37

  PD (/km2, 2015) Barangay Klase Lalawigan Unnamed: 7 Unnamed: 8 Unnamed: 9
0             456       31   Mun      Abra        NaN        NaN        NaN
1              16        8   Mun      Abra        NaN        NaN        NaN
2             160       21   Mun      Abra        NaN        NaN        NaN
3              39        4   Mun      Abra        NaN        NaN        NaN
4              18        4   Mun      Abra        NaN        NaN        NaN

C:\Users\Gio\AppData\Local\Temp\ipykernel_45412\4244604200.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

In [4]:
df

,Lungsod o bayan,Populasyon (2015)[1],Lawak/sukat (km2)[i][2][3],"PD (/km2, 2015)",Barangay,Klase,Lalawigan,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Bangued,48163,105.70,456,31,Mun,Abra,NaN,NaN,NaN
1,Boliney,3573,216.92,16,8,Mun,Abra,NaN,NaN,NaN
2,Bucay,17115,107.17,160,21,Mun,Abra,NaN,NaN,NaN
3,Bucloc,2501,63.77,39,4,Mun,Abra,NaN,NaN,NaN
4,Daguioman,2088,114.37,18,4,Mun,Abra,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1630,Siay,41572,313.66,133,29,Mun,Zamboanga Sibugay,NaN,NaN,NaN
1631,Talusan,29969,58.16,515,14,Mun,Zamboanga Sibugay,NaN,NaN,NaN
1632,Titay,49673,350.44,142,30,Mun,Zamboanga Sibugay,NaN,NaN,NaN
1633,Tungawan,42030,473.28,89,25,Mun,Zamboanga Sibugay,NaN,NaN,NaN
1634,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...

In [17]:
df_cleaned = df.drop(columns=["Populasyon (2015)[1]", "Lawak/sukat (km2)[i][2][3]", "Barangay", "Klase", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9"] )
df_cleaned

,Lungsod o bayan,"PD (/km2, 2015)",Lalawigan
0,Bangued,456,Abra
1,Boliney,16,Abra
2,Bucay,160,Abra
3,Bucloc,39,Abra
4,Daguioman,18,Abra
...,...,...,...
1630,Siay,133,Zamboanga Sibugay
1631,Talusan,515,Zamboanga Sibugay
1632,Titay,142,Zamboanga Sibugay
1633,Tungawan,89,Zamboanga Sibugay
1634,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...

In [20]:
df = df_cleaned.drop(df_cleaned.columns[1], axis=1)
df

,Lungsod o bayan,Lalawigan
0,Bangued,Abra
1,Boliney,Abra
2,Bucay,Abra
3,Bucloc,Abra
4,Daguioman,Abra
...,...,...
1630,Siay,Zamboanga Sibugay
1631,Talusan,Zamboanga Sibugay
1632,Titay,Zamboanga Sibugay
1633,Tungawan,Zamboanga Sibugay
1634,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...

In [21]:
df

,Lungsod o bayan,Lalawigan
0,Bangued,Abra
1,Boliney,Abra
2,Bucay,Abra
3,Bucloc,Abra
4,Daguioman,Abra
...,...,...
1630,Siay,Zamboanga Sibugay
1631,Talusan,Zamboanga Sibugay
1632,Titay,Zamboanga Sibugay
1633,Tungawan,Zamboanga Sibugay
1634,↑ Lahat ng mga datos para sa lawak/sukat ng lu...,↑ Lahat ng mga datos para sa lawak/sukat ng lu...

In [ ]:
df = df.drop(df.index[1634]).reset_index(drop=True)

In [23]:
df

     Lungsod o bayan          Lalawigan
0            Bangued               Abra
1            Boliney               Abra
2              Bucay               Abra
3             Bucloc               Abra
4          Daguioman               Abra
...              ...                ...
1629    Roseller Lim  Zamboanga Sibugay
1630            Siay  Zamboanga Sibugay
1631         Talusan  Zamboanga Sibugay
1632           Titay  Zamboanga Sibugay
1633        Tungawan  Zamboanga Sibugay

[1634 rows x 2 columns]

In [24]:
df.to_csv("cities_regions_raw.csv", index=False)